function p3 = p_third_joint(q1,q2)
%P3
%    P3 = P3(Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Oct-2021 18:33:08

t2 = sin(q2);
p3 = [t2.*cos(q1).*(-2.0./5.0);t2.*sin(q1).*(-2.0./5.0);cos(q2).*(2.0./5.0)+3.1e+1./1.0e+2];
